### ISSUE TITLE
SSL Verification Failed

### ISSUE THREAD

**Issue by wittling** [openbaton/openbaton-cli#4]
The openbaton-cli seems to work fine with http, but on https, I am getting a certificate verification failure when I run it. 

Additional Info: I have both Python 2.7.12 as well as Python3 on this system. I have run it with Python 3.5.2 (python3 openbaton) but when I run it with Python 3 I get an import error (tabulate module). When I run it with Python 2 (python openbaton) it will work properly when nfvo configure on port 8080 with https, but not on port 8443 https (error below).

This might be related to Python Requests. I have considered issuing my own self-signed certificate and putting that into the pk12 file of the nfvo, but everything else in openbaton seems to be working just fine so I hesitate to do that. Anyone have any suggestions?

openbaton@ubuntu-openbaton:/opt/wittling/openbaton/develop-branch/openbaton-cli# env | grep OB
OB_NFVO_PORT=8443
OB_NFVO_IP=172.31.0.136
OB_PASSWORD=openbaton
OB_USERNAME=openbaton-user
OB_PROJECT_ID=b4cf42ce-3b12-40b7-9edf-a9c851f026ab
openbaton@ubuntu-openbaton:/opt/wittling/openbaton/develop-branch/openbaton-cli# ./openbaton -pid ${OB_PROJECT_ID} -u openbaton-user -p openbaton -d ip 172.31.0.136 --nfvo-port 8443 project list
usage: openbaton [-h] [-pid PROJECT_ID] [-u USERNAME] [-p PASSWORD] [-d]
                 [-ip NFVO_IP] [--nfvo-port NFVO_PORT]
                 {project,vnfci,vdu,log,vnfd,csarnsd,nsd,csarvnfd,vim,vnfr,service,user,key,vnfpackage,nsr,event,market}
                 {list,show,delete,create} [params [params ...]]
openbaton: error: argument agent: invalid choice: 'ip' (choose from 'project', 'vnfci', 'vdu', 'log', 'vnfd', 'csarnsd', 'nsd', 'csarvnfd', 'vim', 'vnfr', 'service', 'user', 'key', 'vnfpackage', 'nsr', 'event', 'market')
root@ubuntu-openbaton:/opt/wittling/openbaton/develop-branch/openbaton-cli# ./openbaton -pid ${OB_PROJECT_ID} -u openbaton-user -p openbaton -d -ip 172.31.0.136 --nfvo-port 8443 project list

DEBUG:org.openbaton.cli.MainAgent:username 'openbaton-user'
DEBUG:org.openbaton.cli.MainAgent:project_id 'b4cf42ce-3b12-40b7-9edf-a9c851f026ab'
DEBUG:org.openbaton.cli.MainAgent:nfvo_ip '172.31.0.136'
DEBUG:org.openbaton.cli.MainAgent:nfvo_port '8443'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 172.31.0.136

**ERROR: HTTPSConnectionPool(host='172.31.0.136', port=8443): Max retries exceeded with url: /oauth/token (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))**

**Comment by lorenzotomasini** [comment]
is it a self signed certificate?

**Comment by ananyajh** [comment]
Hi @wittling . I tried to recreate the issue in Python 2.7 and 3.5 by enabling the "Enable SSL" section in openbaton-nfvo.properties file. However, I could not reproduce it. I am getting the desired output, along with a InsecureRequestWarning. Let us know if the error still persists.

**Comment by marcellom** [comment]
This looks like an old issue. @wittling if the issue still persists, please create a new issue and the steps for reproducing it.
